In [1]:
!pip install ultralytics

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 921.9/921.9 kB 15.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 2.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 96.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 77.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 43.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 1.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 4.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 17.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 17.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 5.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 88.6 MB/s eta 0:00:00
  Attempting uninstall: nvidia-nvjitlink-cu12
    Found existing installation: nvidia-nvjitlink-cu12 12.5.82
    Uninstal

In [2]:
from ultralytics import YOLO

path = 'drive/MyDrive/isolated_cube_dataset/color_identity_data.yaml'
model = YOLO('sticker_labeler.pt')

# results = model.train(data=path, epochs=10)


Creating new Ultralytics Settings v0.0.6 file ✅ 
View Ultralytics Settings with 'yolo settings' or at '/root/.config/Ultralytics/settings.json'
Update Settings with 'yolo settings key=value', i.e. 'yolo settings runs_dir=path/to/dir'. For help see https://docs.ultralytics.com/quickstart/#ultralytics-settings.


In [3]:
metrics = model.val()

Ultralytics 8.3.80 🚀 Python-3.11.11 torch-2.5.1+cu124 CUDA:0 (NVIDIA L4, 22693MiB)
YOLO11n summary (fused): 100 layers, 2,583,322 parameters, 0 gradients, 6.3 GFLOPs


100%|██████████| 755k/755k [00:00<00:00, 24.9MB/s]
val: Scanning /content/drive/MyDrive/isolated_cube_dataset/val/labels.cache... 100 images, 0 backgrounds, 0 corrupt: 100%|██████████| 100/100 [00:00<?, ?it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:07<00:00,  1.07s/it]


                   all        100        898       0.97      0.984      0.975      0.925
                 green         91        150      0.916      0.967      0.934      0.876
                  blue         81        158      0.981      0.987      0.994      0.968
                orange         81        157      0.999          1      0.995      0.927
                   red         86        149      0.994      0.993      0.995      0.929
                yellow         73        135      0.991          1      0.995      0.975
                 white         86        149      0.941      0.956      0.938      0.876
Speed: 2.1ms preprocess, 12.8ms inference, 0.0ms loss, 5.6ms postprocess per image
Results saved to runs/detect/val


In [3]:
import cv2
img = cv2.imread('drive/MyDrive/IMG_7682.jpeg')
x1, y1, x2, y2 = [2326, 1336, 3928, 2938]
x1, y1, x2, y2 = [2444, 1333, 4009, 2904]
img = img[x1:x2, y1:y2]
inference = model(img)
print(inference)
for result in inference:
    boxes = result.boxes  # Boxes object for bounding box outputs
    masks = result.masks  # Masks object for segmentation masks outputs
    keypoints = result.keypoints  # Keypoints object for pose outputs
    probs = result.probs  # Probs object for classification outputs
    obb = result.obb  # Oriented boxes object for OBB outputs
    result.show()  # display to screen


Output hidden; open in https://colab.research.google.com to view.

In [4]:
infer = inference[0]

print(infer.boxes.xywh)
print(infer.boxes.xywhn)

tensor([[1322.3223,  776.1529,  401.5991,  420.0983],
        [ 328.4441, 1271.7915,  404.7917,  420.6027],
        [ 809.6631,  774.6405,  411.7411,  411.3293],
        [1335.1871,  269.0146,  390.7100,  392.1947],
        [ 308.3618,  266.9710,  397.7913,  392.3502],
        [1353.4329, 1290.1746,  405.5701,  409.5728],
        [ 836.8508, 1306.4636,  429.0264,  413.5719],
        [ 303.2045,  770.2264,  412.3157,  422.3707],
        [ 835.1979,  273.9933,  419.0718,  391.4734]])
tensor([[0.8417, 0.4959, 0.2556, 0.2684],
        [0.2091, 0.8126, 0.2577, 0.2688],
        [0.5154, 0.4950, 0.2621, 0.2628],
        [0.8499, 0.1719, 0.2487, 0.2506],
        [0.1963, 0.1706, 0.2532, 0.2507],
        [0.8615, 0.8244, 0.2582, 0.2617],
        [0.5327, 0.8348, 0.2731, 0.2643],
        [0.1930, 0.4922, 0.2625, 0.2699],
        [0.5316, 0.1751, 0.2668, 0.2501]])


In [5]:
import torch
import numpy as np
from sklearn.cluster import KMeans

clusters = KMeans(n_clusters=3).fit_predict(infer.boxes.xywhn[:,1].reshape(-1, 1))

order = np.argsort(clusters)
clustered = torch.cat((infer.boxes.xywhn[order], torch.Tensor(order).unsqueeze(1)),dim=1)
min_val, max_val = min(clustered[:,1]), max(clustered[:,1])

groups = [clustered[:3], clustered[3:6], clustered[6:]]

rows = [None for _ in range(3)]
for group in groups:
  if abs(group[0,1] - min_val) <= 0.1:
    rows[0] = group
  elif abs(group[0,1] - max_val) <= 0.1:
    rows[2] = group
  else:
    rows[1] = group

for i, row in enumerate(rows):
  ids = torch.argsort(row[:,0], descending=False)
  rows[i] = row[ids]

sorted = torch.cat(tuple(rows), dim=0)
print(sorted)
print(infer.boxes.xywhn)
idxs = sorted[:,4].to(dtype=int)
print(idxs)
print(infer.boxes.cls)
print(infer.boxes.cls[idxs])
print('prediction order')
for i in infer.boxes.cls:
  print(infer.names[int(i.item())])
print('sorted order')
for i in infer.boxes.cls[idxs]:
  print(infer.names[int(i.item())])
# inner_idx = torch.argsort(infer.boxes.xywh[:, 0])
# inner_sort = infer.boxes.xywh[inner_idx]

# outer_idx = torch.argsort(inner_sort[:, 1], stable=True)

# inner_sort[outer_idx]

tensor([[0.1963, 0.1706, 0.2532, 0.2507, 4.0000],
        [0.5316, 0.1751, 0.2668, 0.2501, 8.0000],
        [0.8499, 0.1719, 0.2487, 0.2506, 3.0000],
        [0.1930, 0.4922, 0.2625, 0.2699, 7.0000],
        [0.5154, 0.4950, 0.2621, 0.2628, 2.0000],
        [0.8417, 0.4959, 0.2556, 0.2684, 0.0000],
        [0.2091, 0.8126, 0.2577, 0.2688, 1.0000],
        [0.5327, 0.8348, 0.2731, 0.2643, 6.0000],
        [0.8615, 0.8244, 0.2582, 0.2617, 5.0000]])
tensor([[0.8417, 0.4959, 0.2556, 0.2684],
        [0.2091, 0.8126, 0.2577, 0.2688],
        [0.5154, 0.4950, 0.2621, 0.2628],
        [0.8499, 0.1719, 0.2487, 0.2506],
        [0.1963, 0.1706, 0.2532, 0.2507],
        [0.8615, 0.8244, 0.2582, 0.2617],
        [0.5327, 0.8348, 0.2731, 0.2643],
        [0.1930, 0.4922, 0.2625, 0.2699],
        [0.5316, 0.1751, 0.2668, 0.2501]])
tensor([4, 8, 3, 7, 2, 0, 1, 6, 5])
tensor([4., 3., 3., 3., 1., 4., 1., 1., 0.])
tensor([1., 0., 3., 1., 3., 4., 3., 1., 4.])
prediction order
yellow
red
red
red
blue
yel

In [7]:
def sort_prediction(results):
  """
  From yolo results object class, return sorted prediction array and associated indices
  """
  clusters = KMeans(n_clusters=3).fit_predict(results.boxes.xywhn[:,1].reshape(-1, 1))

  order = np.argsort(clusters)
  clustered = torch.cat((results.boxes.xywhn[order], torch.Tensor(order).unsqueeze(1)),dim=1)
  min_val, max_val = min(clustered[:,1]), max(clustered[:,1])

  groups = [clustered[:3], clustered[3:6], clustered[6:]]

  rows = [None for _ in range(3)]
  for group in groups:
    if abs(group[0,1] - min_val) <= 0.1:
      rows[0] = group
    elif abs(group[0,1] - max_val) <= 0.1:
      rows[2] = group
    else:
      rows[1] = group

  for i, row in enumerate(rows):
    ids = torch.argsort(row[:,0], descending=False)
    rows[i] = row[ids]

  sorted = torch.cat(tuple(rows), dim=0)
  idxs = sorted[:,4].to(dtype=int)


  return results.boxes.cls[idxs], idxs

print(sort_prediction(infer)[0])

tensor([[1., 0., 3.],
        [1., 3., 4.],
        [3., 1., 4.]])


In [58]:
import math

def roundup(x):
  return int(math.ceil(x / 100.0)) * 100

copyed = infer.boxes.xywh.cpu()
copyed[:, ]
#blue green red blue red yellow red blue yellow
for i in infer.boxes.cls[inner_idx][outer_idx]:
  print(infer.names[int(i.item())])



tensor([[1322.3092,  776.1663,  401.6492,  420.2213],
        [ 328.4271, 1271.7921,  404.8255,  420.6814],
        [ 809.6564,  774.5879,  411.7686,  411.3223],
        [1335.2134,  269.0463,  390.7329,  392.1724],
        [ 308.3692,  267.0243,  397.8464,  392.3170],
        [1353.3892, 1290.1721,  405.5707,  409.5895],
        [ 836.8398, 1306.4417,  429.0672,  413.5717],
        [ 303.1826,  770.2252,  412.2759,  422.4427],
        [ 835.1713,  274.0200,  419.1410,  391.4645]])
blue
red
green
blue
red
yellow
red
yellow
blue


In [10]:
infer

ultralytics.engine.results.Results object with attributes:

boxes: ultralytics.engine.results.Boxes object
keypoints: None
masks: None
names: {0: 'green', 1: 'blue', 2: 'orange', 3: 'red', 4: 'yellow', 5: 'white'}
obb: None
orig_img: array([[[238, 231, 216],
        [238, 231, 216],
        [238, 231, 216],
        ...,
        [211, 216, 214],
        [210, 215, 213],
        [209, 214, 212]],

       [[237, 230, 215],
        [237, 230, 215],
        [237, 230, 215],
        ...,
        [210, 215, 213],
        [209, 214, 212],
        [208, 213, 211]],

       [[236, 229, 214],
        [236, 229, 214],
        [236, 229, 214],
        ...,
        [207, 212, 210],
        [207, 212, 210],
        [207, 212, 210]],

       ...,

       [[ 66,  85, 130],
        [ 68,  87, 132],
        [ 66,  85, 130],
        ...,
        [ 59,  78, 123],
        [ 59,  78, 123],
        [ 60,  79, 124]],

       [[ 65,  84, 129],
        [ 67,  86, 131],
        [ 67,  86, 131],
        ...,
     

In [ ]:
model.export()

Ultralytics 8.3.78 🚀 Python-3.11.11 torch-2.5.1+cu124 CPU (Intel Xeon 2.00GHz)

PyTorch: starting from 'runs/detect/train/weights/best.pt' with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 5, 8400) (5.2 MB)

TorchScript: starting export with torch 2.5.1+cu124...
TorchScript: export success ✅ 3.0s, saved as 'runs/detect/train/weights/best.torchscript' (10.4 MB)

Export complete (4.6s)
Results saved to /content/runs/detect/train/weights
Predict:         yolo predict task=detect model=runs/detect/train/weights/best.torchscript imgsz=640  
Validate:        yolo val task=detect model=runs/detect/train/weights/best.torchscript imgsz=640 data=drive/MyDrive/simulated_cube_dataset/data.yaml  
Visualize:       https://netron.app


'runs/detect/train/weights/best.torchscript'